import { Inter } from "next/font/google";
import Navigation from "./components/navigation";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import "./globals.css";
import { Providers } from "./redux/provider";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>
          <ToastContainer />
          <header className="flex flex-col items-center justify-center bg-gray-100">
            <Link href="/">
              <img
                src="/spnegocios.png"
                className="rounded-md mb-6 max-w-xs mt-6"
                alt="Logo"
              ></img>
            </Link>
          </header>
          <nav>
            <Navigation></Navigation>
          </nav>
          <main className="m-6 font-roboto">{children}</main>
        </body>
      </Providers>
    </html>
  );
}
